services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./data:/var/lob/mysql
    
    ports:
    - 3307:3307
    networks: 
    - bootapp

  blogging-app-service:
    build: C:\Users\Admin\Documents\ProjectRepo's\blog-application
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/blog_app?createDatabaseIfNotExist=true
      - spring.datasource.username=root 
      - spring.datasource.password=root 
    ports: 
    - 8080:8080
    networks: 
    - bootapp
 
networks: 
 bootapp:
  